[tool.poetry]
name = "sample"
version = "0.1.0"
description = ""
authors = ["Ray Xu <megrxu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
