baseURL: "https://service.xugr.me/"
languageCode: "en-us"
title: "Remote Services"
theme: "lagrange"
disableHugoGeneratorInject: true

params:
  author: "Ray"
  googleFonts: "https://fonts.googleapis.com/css2?family=Inter"
  math: false
  cdn:
    url: "https://cdn.xugr.me/"
    section: "blog"
    slot: "img"
  social:
    - name: "Github"
      platform: "github"
      weight: 1
      url: "https://github.com/megrxu/"
    - name: "Keybase"
      platform: "keybase"
      weight: 2
      url: "https://keybase.io/xugr/"
    - name: "Telegram"
      platform: "telegram"
      weight: 3
      url: "https://t.me/TyteKa"
